"""
vault init command - Initialize Vault in your project.

Creates a .env file with required configuration.
"""

import os
from pathlib import Path

import typer
from rich.console import Console
from rich.prompt import Prompt, Confirm

console = Console()


ENV_TEMPLATE = """# Vault Configuration
# Generated by: vault init

# Supabase Configuration
# Get these from: https://app.supabase.com/project/_/settings/api
VAULT_SUPABASE_URL={supabase_url}
VAULT_SUPABASE_KEY={supabase_key}

# Optional: Anon key for client-side operations
# VAULT_SUPABASE_ANON_KEY=your-anon-key

# Database Schema (default: public)
# VAULT_SCHEMA=public

# Feature Flags
# VAULT_AUTO_MIGRATE=false
# VAULT_ENABLE_AUDIT_LOG=true

# Debug
# VAULT_DEBUG=false
"""


def init_command(
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing .env file",
    ),
) -> None:
    """
    Initialize Vault in your project.

    Creates a .env file with required Supabase configuration.

    Example:
        $ vault init
        $ vault init --force  # Overwrite existing .env
    """
    console.print("\n[bold cyan]Vault Initialization[/bold cyan]")
    console.print("Setting up Vault in your project\n")

    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists() and not force:
        console.print("[yellow]Warning:[/yellow] .env file already exists")
        overwrite = Confirm.ask("Do you want to overwrite it?", default=False)
        if not overwrite:
            console.print("[red]Aborted[/red]")
            raise typer.Exit(1)

    # Prompt for configuration
    console.print("[bold]Supabase Configuration[/bold]")
    console.print("You can find these at: https://app.supabase.com/project/_/settings/api\n")

    supabase_url = Prompt.ask(
        "Supabase URL",
        default="https://xxx.supabase.co",
    )

    # Validate URL format
    if not supabase_url.startswith("https://"):
        console.print("[red]Error:[/red] Supabase URL must start with https://")
        raise typer.Exit(1)

    supabase_key = Prompt.ask(
        "Supabase Service Role Key",
        password=True,
    )

    if not supabase_key or len(supabase_key) < 10:
        console.print("[red]Error:[/red] Invalid Supabase key")
        raise typer.Exit(1)

    # Create .env file
    env_content = ENV_TEMPLATE.format(
        supabase_url=supabase_url,
        supabase_key=supabase_key,
    )

    env_file.write_text(env_content)

    console.print(f"\n[green]✓[/green] Created .env file")

    # Show next steps
    console.print("\n[bold]Next Steps:[/bold]")
    console.print("1. Review and update .env file if needed")
    console.print("2. Run migrations: [cyan]vault migrate[/cyan]")
    console.print("3. Start using Vault in your code\n")

    # Show example code
    console.print("[bold]Example Usage:[/bold]")
    console.print("""
[cyan]from vault import Vault

# Initialize Vault (loads from .env automatically)
vault = Vault()

# Create a user
user = await vault.users.create(
    email="user@example.com",
    password="secure123"
)

# Create an organization
org = await vault.orgs.create(
    name="Acme Corp",
    slug="acme-corp"
)[/cyan]
""")

    console.print("[green]✓[/green] Vault initialized successfully!\n")
